#ifndef __S2_TOWSON_BU_H__
#define __S2_TOWSON_BU_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_TOWSON_BU_UPDATE_CONFIGURATIONS_DIG_INPUT 0


/*
* ANALOG_INPUT
*/




/*
* DIGITAL_OUTPUT
*/
#define __S2_TOWSON_BU_BU_113_FB_DIG_OUTPUT 0
#define __S2_TOWSON_BU_BU_102_FB_DIG_OUTPUT 1
#define __S2_TOWSON_BU_BU_117_FB_DIG_OUTPUT 2


/*
* ANALOG_OUTPUT
*/



/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/
#define __S2_TOWSON_BU_DATABASELOCATION$_STRING_PARAMETER 10
#define __S2_TOWSON_BU_DATABASENAME$_STRING_PARAMETER 11
#define __S2_TOWSON_BU_DATABASELOCATION$_PARAM_MAX_LEN 5
CREATE_STRING_STRUCT( S2_TOWSON_BU, __DATABASELOCATION$, __S2_TOWSON_BU_DATABASELOCATION$_PARAM_MAX_LEN );
#define __S2_TOWSON_BU_DATABASENAME$_PARAM_MAX_LEN 50
CREATE_STRING_STRUCT( S2_TOWSON_BU, __DATABASENAME$, __S2_TOWSON_BU_DATABASENAME$_PARAM_MAX_LEN );


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_TOWSON_BU_SFILES$_STRING_MAX_LEN 100
CREATE_STRING_STRUCT( S2_TOWSON_BU, __SFILES$, __S2_TOWSON_BU_SFILES$_STRING_MAX_LEN );
#define __S2_TOWSON_BU_SDATABASE$_STRING_MAX_LEN 65000
CREATE_STRING_STRUCT( S2_TOWSON_BU, __SDATABASE$, __S2_TOWSON_BU_SDATABASE$_STRING_MAX_LEN );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_TOWSON_BU )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_STRING_STRUCT( S2_TOWSON_BU, __SFILES$ );
   DECLARE_STRING_STRUCT( S2_TOWSON_BU, __SDATABASE$ );
   DECLARE_STRING_STRUCT( S2_TOWSON_BU, __DATABASELOCATION$ );
   DECLARE_STRING_STRUCT( S2_TOWSON_BU, __DATABASENAME$ );
};

START_NVRAM_VAR_STRUCT( S2_TOWSON_BU )
{
};



#endif //__S2_TOWSON_BU_H__

